### ISSUE TITLE
ERROR: Service 'iris' failed to build : Build failed

### ISSUE THREAD

**Issue by mwaseem75** [grongierisc/iris-python-template#1]
Hi

I am getting below error while composing up

failed to solve with frontend dockerfile.v0: failed to create LLB definition: containers.intersystems.com/intersystems/irishealth-community:2021.2.0.649.0: not found

Thanks

**Comment by grongierisc** [comment]
Solved by bumping iris version to  containers.intersystems.com/intersystems/irishealth-community:2021.2.0.6**51**.0
